### ISSUE TITLE
gson.fromJson parses empty JSON like "{}" successfully into non-null properties of data class

### ISSUE THREAD

**Issue by rawcheeselatte** [google/gson#2378] opened 2023-04-24 09:31 UTC
# Gson version
implementation group: 'com.google.code.gson', name: 'gson', version: '2.10.1'

# System environment
------------------------------------------------------------
Gradle 7.6.1
------------------------------------------------------------

Build time:   2023-02-24 13:54:42 UTC
Revision:     3905fe8ac072bbd925c70ddbddddf4463341f4b4

Kotlin:       1.7.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.7 (Eclipse Adoptium 17.0.7+7)
OS:           Mac OS X 13.3.1 aarch64

# Description

given a data class defined with non-null object like
```
data class Duck(
    val wings: String
)
```
when give a JSON string like
"{}" or
"{wings=null}" or
"{feather=123}"

## Expected behavior

gson would throw an exception since my duck must have wings

## Actual behavior

gson successfully parsed my duck with null of wings

**Comment by xjarkrof** [comment] 2023-04-24 17:26
Actually the behavior is correct. You did not specify anywhere the Duck must have non null (or not empty) wings. The `val` only means not modifiable after creation ?!

**Comment by eamonnmcmanus** [comment] 2023-04-24 17:43
I'm assuming this is Kotlin, so `val wings: String` means that `wings` cannot be null. (Otherwise it would be `String?` rather than `String`.)

I think it would be good if we had a `TypeAdapterFactory` for Kotlin `data` classes like this. Then it could correctly reject inputs that leave `wings` null. Meanwhile, [Moshi](https://github.com/square/moshi) supports Kotlin better than Gson does.

**Comment by Marcono1234** [comment] 2023-04-24 22:00
> [Moshi](https://github.com/square/moshi) supports Kotlin better than Gson does.

Yes, it appears Gson just happens to support Kotlin in many cases, but at least until now there hasn't been any official support or considerations for it I think, so it would be better to use a JSON library with explicit Kotlin support (Moshi, Jackson, kotlinx.serialization, ...).

Probably a duplicate of #1657; @eamonnmcmanus do you think we can close this issue here then?

**Comment by eamonnmcmanus** [comment] 2023-04-24 22:28
Yes, this is a dup of #1657.

**Closed by eamonnmcmanus** 2023-04-24 22:28 UTC
Labels: bug

**Comment by zxutyro** [comment] 2023-04-25 00:46
the problem described above indeed is in Kotlin, thanks all
