### ISSUE TITLE
no method to parse json in strict mdoe

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#577] opened 2015-03-19 18:34 UTC
```
there is no method such as GsonBuilder.setLenient(false)  to parse json string 
in strict mode. 
i need gson throw an error if it contains comment.
```

Original issue reported on code.google.com by `dingweiw...@gmail.com` on 30 Apr 2014 at 2:42

**Comment by Marcono1234** [comment] 2022-07-25 19:22
Unfortunately Gson is lenient by default due to legacy reasons. However, at least this is now documented since #2122, and the `Gson` documentation will in the next release also mention workarounds for this.

This issue might also be a duplicate of #372.

**Closed** 2022-07-26 03:42 UTC
