### ISSUE TITLE
JsonAdapter annotation with JsonDeserializer value and nullSafe = false not work

### ISSUE THREAD

**Issue by huajianjiang** [google/gson#1917] opened 2021-07-06 05:58 UTC
JsonAdapter annotation  + JsonDeserializer + false nullSafe not working, deserialize not called.
but JsonAdapter annotation  + TypedAdapter + false nullSafe is worked.

for example:

```
public class User {
    @JsonAdapter(value = GenderDeserializer.class, nullSafe = false)
    private Gender gender;
}

public static class GenderDeserializer implements JsonDeserializer<Gender> {
          
           // When gender is null, deserialize method not called even with nullSafe = false annotation value.

           @Override
           public Gender deserialize(JsonElement json, Type typeOfT,
                JsonDeserializationContext context) throws JsonParseException
           { 
                  return Gender.toGender(json.getAsString()); 
           }
}
```

**Comment by Marcono1234** [comment] 2021-07-06 15:38
Looks like this has already been reported as #1553.

**Comment by huajianjiang** [comment] 2021-07-08 08:01
@Marcono1234  Why not merge solutions PR?

**Comment by Marcono1234** [comment] 2021-07-08 21:59
I am not a member of this project, I cannot merge any pull requests.

**Comment by Marcono1234** [comment] 2022-08-03 23:24
Duplicate of #1553

**Closed by Marcono1234** 2022-08-03 23:24 UTC
