### ISSUE TITLE
Encountered {} issue with streaming output JSON

### ISSUE THREAD

**Issue by iwangjie** [google/gson#1635] opened 2019-12-20 02:35 UTC
When I used SpringFarmeWork 4.2.x, I found that the default Gson message converter used by Spring incorrectly converted my Json and the business failed.

I tried to trace the code, and finally confirmed the method of Gson's conversion through the stream 
 `toJson (Object src, Type typeOfSrc, Appendable writer) ` There may be a problem, the following is the code I locate.

在ReflectiveTypeAdapterFactory中
![image](https://user-images.githubusercontent.com/23075587/71225471-b5d1d580-2313-11ea-8a50-2230aab5719b.png)

This judgment directly led to the fact that when the Type is an interface instead of considering the implementation class.

Obtained, this Type object should pass the Type of the implementation class. Sorry, my programming experience is preferred, and I cannot analyze this cause in more depth.

Attach the demo code I created：
[https://github.com/iwangjie/GsonTest](https://github.com/iwangjie/GsonTest)

**Comment by iwangjie** [comment] 2019-12-20 02:37
If I pass the correct implementation class Type instance, the result is normal, but Gson for Spring integration does not

**Comment by iwangjie** [comment] 2019-12-20 03:33
Attach Spring's Help Link：[https://github.com/spring-projects/spring-framework/issues/24234](https://github.com/spring-projects/spring-framework/issues/24234)

**Comment by lyubomyr-shaydariv** [comment] 2019-12-20 18:13
Not a bug and this is how it was initially designed: when you serialize an object you _can_ specify the bottom-most class you need serialization to stop at. Consider the following example:

```java
interface Page { }
class IntermediatePage implements Page { String inIntermediate; }
class ConcretePage extends IntermediatePage { String inConcrete; }
```

```java
final Gson gson = new Gson();
final ConcretePage page = new ConcretePage();
page.inIntermediate = "intermediate";
page.inConcrete = "concrete";
for ( final Class<?> c : new Class<?>[]{ Page.class, IntermediatePage.class, ConcretePage.class } ) {
	System.out.println(c.getSimpleName() + ": " + gson.toJson(page, c));
}
```

This code will produce

```
Page: {}
IntermediatePage: {"inIntemediate":"intermediate"}
ConcretePage: {"inConcrete":"concrete","inIntemediate":"intermediate"}
```

Such design also guarantees the serialization+deserialization _symmetry_. For example, when you deserialize `Page.class` -- what it exactly is: `IntemediatePage` or `ConcretePage`? When you deserialize `IntemediatePage` -- what's it real type, `IntemediatePage` or `ConcretePage`? Also, interfaces cannot declare any instance fields, so this is why `ReflectiveTypeAdapterFactory` does the check.

**Comment by Marcono1234** [comment] 2022-08-20 14:26
I agree with @lyubomyr-shaydariv. When you use the `toJson` overloads with `Type` parameter you are telling Gson to serialize the object exactly as that type, and not as the runtime type. If that is not desired you should use the `toJson` overloads without `Type` parameter.
If that is (for whatever reason) not possible in your scenario, you could either register a [`TypeAdapterFactory`](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/TypeAdapterFactory.html) which for that specific `Page` interface returns the adapter for `PageImpl` instead:
```java
public class PageAdapterFactory implements TypeAdapterFactory {
  @Override
  public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
    if (type.getRawType() == Page.class) {
      // Important: This is not safe; if a Page implementation other than PageImpl
      // is used this could lead to ClassCastExceptions
      @SuppressWarnings("unchecked")
      TypeAdapter<T> r = (TypeAdapter<T>) gson.getAdapter(TypeToken.get(PageImpl.class));
      return r;
    }
    return null;
  }
}

...

Gson gson = new GsonBuilder()
    .registerTypeAdapterFactory(new PageAdapterFactory())
    .create();
```
(this will not work properly for deserialization because the type argument for `<T>` is not preserved; can be adjusted to handle that)

Alternatively you could instead register a `TypeAdapterFactory` which creates a `TypeAdapter` whose `write` method always looks up the adapter for the runtime type; but that might have undesired effects on other unrelated interfaces.

I am going to close this because I think Gson behaves as intended here (though I am not a direct project member).

**Closed by Marcono1234** 2022-08-20 14:26 UTC
