### ISSUE TITLE
[Feature request]  @NotExpose 

### ISSUE THREAD

**Issue by patpatpat123** [google/gson#1489] opened 2019-03-11 14:22 UTC
Hello Gson Team,

Thank you so much for this project.
Is it possible to have  @NotExpose alongside @Expose in a next release?
@Expose is great.
However, in a case there a class has like lot lot lot lot lot of fields, but only one sensitive field to not expose, the current approach is either:
write (lot lot lot lot lot minus one field of @Expose) + .excludeFieldsWithoutExposeAnnotation()
or, writing an entire .setExclusionStrategies() block just for this one field.

It will be great if you can consider adding this @NotExpose.
Thank you very much for this project.

**Comment by geertberkers** [comment] 2019-05-01 21:54
You could just use @Transcient ;)

**Comment by rubenferreira1997** [comment] 2019-10-02 22:28
Would like to see this feature as well. It's boring to write 10 Exposes when you only want to exclude one field. Transient keyword it's not a solution, you can't accomplish this `@Expose(serialize = false, deserialize = true)`.

**Comment by Marcono1234** [comment] 2022-08-03 23:56
Duplicate of #1020

I think the solution described in https://github.com/google/gson/issues/1020#issuecomment-310280022, by implementing an `ExclusionStrategy` which checks for your custom field annotation, would solve this issue.

**Closed by Marcono1234** 2022-08-03 23:56 UTC

**Comment by patpatpat123** [comment] 2022-08-04 01:51
ok
