### ISSUE TITLE
Gson does not use RuntimeTypeAdapterFactory's type adapter

### ISSUE THREAD

**Issue by SylvainVISSIERE-GUERINET** [google/gson#969] opened 2016-12-02 11:04 UTC
Hello,

I tried to use `RuntimeTypeAdapterFactory` to specify to `Gson` which type adapter should be used to handle a hierarchy of class extending an abstract class. I've declared the factory's base class using the top abstract class and registered its subclasses using `GsonBuilder.registerTypeAdapterFactory`.
```java
pBuilder.registerTypeAdapterFactory(typeAdapterFactory); // Won't work.
```
My `Gson` instance had the factory registered but it was not using it. After some debug, I noticed that `Gson.toJson(Object)` was getting the wrong type adapter ([here](https://github.com/google/gson/blob/master/gson/src/main/java/com/google/gson/Gson.java#L661)) as it is taking the concrete class type and not the abstract one. I managed to fix the issue by using `registerTypeHierarchyAdapter` instead.

here is my hack :
```java
pBuilder.registerTypeHierarchyAdapter(<AbstractType>, typeAdapterFactory.create(new Gson(), TypeToken.get(<AbstractType>)));
```

I don't know if it is an issue from GSON library or the RuntimeTypeAdapterFactory. I mainly wanted to spot the issue and share my hack.

**Comment by MOZGIII** [comment] 2017-10-02 20:21
How can this be fixed?

**Comment by NightlyNexus** [comment] 2017-10-02 21:37
I'm fairly certain the RuntimeTypeAdapterFactory works as intended; can you share a failing test?

**Comment by MOZGIII** [comment] 2017-10-03 00:10
I think I can make one, just a sec

**Comment by MOZGIII** [comment] 2017-10-03 01:41
I can confirm `gson` works as intended for me. The issue I was experiencing was caused by not calling `registerTypeAdapterFactory` (shame on me). I've also played with tests, and they proved `gson`'s fine.

**Comment by Marcono1234** [comment] 2022-09-18 23:43
Closing this because no complete (small) example was provided. If you are still experiencing this issue with the latest Gson version feel free to comment here.

**Closed by Marcono1234** 2022-09-18 23:43 UTC
