### ISSUE TITLE
Overriding default DateTypeAdapter

### ISSUE THREAD

**Issue by AnixPasBesoin** [google/gson#986] opened 2016-12-27 16:24 UTC
I'm having this issue with overriding the Gson DefaultTypeAdapter.
I created a custom DateTypeAdapter and registered it with when instantiating my Gson object:

        Gson gson = new GsonBuilder().registerTypeAdapter(Date.class, new DateTypeAdapter()).create();

However, my gosn object is not using it when serializing/deserializing dates.

I am using java.util.Date everywhere. So how do I do I override the default DateTypeAdapter?

**Comment by supSep** [comment] 2017-08-11 18:03
Would like to know how to do this as well.

**Comment by naturalwarren** [comment] 2017-08-12 02:57
Whoa that seems broken. Might have to do with the order TypeAdapters are registered in under the hood.

**Comment by caleb-allen** [comment] 2018-02-14 22:52
I ended up using DateTime from the `joda` library which doesn't subclass the java.util.Date class so it doesn't run into these weird issues.

**Comment by captainepoch** [comment] 2022-12-30 19:19
I'm interested in this issue as well, since I ran into a case where I need to add a custom DateTypeAdapter to fix an issue, but I don't see any reply to it.

**Comment by AnixPasBesoin** [comment] 2022-12-30 19:21
@captainepoch here's the link to my original SO question: https://stackoverflow.com/q/41348055/3503855

**Comment by captainepoch** [comment] 2022-12-30 19:24
> @captainepoch here's the link to my original SO question: https://stackoverflow.com/q/41348055/3503855

Oh, thank you! I'll give it an oportunity.

You might want to close this issue, since it seems to be solved in the SO question.

Thanks for sharing it!

**Comment by AnixPasBesoin** [comment] 2022-12-30 19:25
@captainepoch it's not exactly the same issue, though it's a bit related...

**Closed** 2022-12-30 19:25 UTC

**Comment by Marcono1234** [comment] 2023-01-08 22:45
For what it's worth, I cannot reproduce the original issue about being unable to register a type adapter for `java.util.Date` in Gson 2.10.1. In case someone is still experiencing this, the following things might cause this:
- There was indeed a bug in an older Gson version
- `Date.class` in your code is accidentally <code><b>java.sql</b>.Date</code> instead of `java.util.Date`
- Your code is passing subclasses of `Date` to Gson; `GsonBuilder.registerTypeAdapter` only registers an adapter for that specific type, to support subclasses you have to use `registerTypeHierarchyAdapter`
