### ISSUE TITLE
TypeAdapters assertion looses causing throwable

### ISSUE THREAD

**Issue by realdadfish** [google/gson#737] opened 2015-11-16 12:21 UTC
In line https://github.com/google/gson/blob/master/gson/src/main/java/com/google/gson/internal/bind/TypeAdapters.java#L799
an `AssertionError` is thrown in case a `NoSuchFieldException` is triggered. The assertion however looses all context information what field is missing and makes debugging this issue very hard, especially on proguarded builds.

**Comment by swankjesse** [comment] 2015-11-16 13:00
Seems like disabling proguard will always simplify debugging.

**Comment by tommyd3mdi** [comment] 2015-11-16 15:04
Not this time, though. Figured it out that I had a wrong OkHttp proguard configuration after I could hint myself at the missing field by using a custom gson build. Feel free to take this code over:

	diff --git a/gson/src/main/java/com/google/gson/internal/bind/TypeAdapters.java b/gson/src/main/java/com/google/gson/internal/bind/TypeAdapters.java
	index d284dd5..6bb4a1f 100644
	--- a/gson/src/main/java/com/google/gson/internal/bind/TypeAdapters.java
	+++ b/gson/src/main/java/com/google/gson/internal/bind/TypeAdapters.java
	@@ -796,7 +796,7 @@ public final class TypeAdapters {
	           constantToName.put(constant, name);
	         }
	       } catch (NoSuchFieldException e) {
	-        throw new AssertionError();
	+        throw new AssertionError("missing field in " + classOfT, e);
	       }
	     }
	     @Override public T read(JsonReader in) throws IOException {

**Comment by gupta-sachin** [comment] 2016-04-28 07:48
The AssertionError constructor with Throwable is added since Java 1.7 so it will be better to have only a detailed error message here.

**Comment by Marcono1234** [comment] 2022-07-28 23:06
The detailed error message was added by #738 but because this was the used construction does not exist in Java 6 was reduced to only setting the cause by #857.
However, this code was refactored by #1495 to better handle obfuscated enum constant names, so this issue is probably resolved.

**Comment by eamonnmcmanus** [comment] 2022-07-28 23:09
Given how old this issue is and the summary from @Marcono1234 I'm going to close this now. Feel free to reopen or log a new issue if there is still a genuine issue here.

**Closed by eamonnmcmanus** 2022-07-28 23:09 UTC
