### ISSUE TITLE
Do JsonObject/Array too hard to implements Serializable ? 

### ISSUE THREAD

**Issue by qaz4042** [google/gson#1624] opened 2019-11-27 15:11 UTC
I use JsonObject and JsonArray as my entitys's property,and want serialize entitys to cacheManager.
I think it can be inneed a strong demand, using jsonObject/Array as a common object within our Json Features, doesn't it?
And If it can serialize  getter method, gson will be better for user.

**Comment by lyubomyr-shaydariv** [comment] 2019-11-27 17:11
Does Ehcache support custom serializers?

**Comment by Marcono1234** [comment] 2022-07-24 21:38
Sounds like a duplicate of #485.

**Closed** 2022-07-25 17:59 UTC
