### ISSUE TITLE
fromJson throw IllegalAccessError

### ISSUE THREAD

**Issue by Hanry0204** [google/gson#1734] opened 2020-07-08 03:44 UTC
The project uses Gson to serialize the Json returned by the interface. The specific Vo classes and procedures are as follows. After the service starts to run for a period of time, java.lang.IllegalAccessError: com/google/gson/internal/$Gson$Types$GenericArrayTypeImpl error will occur occasionally. The specific procedures and the debug information for the error report are as follows. Has anyone encountered a similar problem?

Best Regards.

**Bean Class：**
```
public class ProjectFlowsVo {
    /**
     * 项目名称
     */
    private String project;
    /**
     * 项目ID
     */
    private int projectId;
    /**
     * 任务流列表
     */
    public Flow[] flows;

    public static class Flow {
        /**
         * 任务流名称
         */
        private String flowId;

        public String getFlow() {
            return flowId;
        }

        public void setFlowId(String flowId) {
            this.flowId = flowId;
        }

        @Override
        public String toString() {
            return "Flow{" +
                    "flow='" + flowId + '\'' +
                    '}';
        }
    }

    public String getProject() {
        return project;
    }

    public int getProjectId() {
        return projectId;
    }

    public List<Flow> getFlows() {
        return Arrays.asList(flows);
    }

    public void setProject(String project) {
        this.project = project;
    }

    public void setProjectId(int projectId) {
        this.projectId = projectId;
    }

    public void setFlows(Flow[] flows) {
        this.flows = flows;
    }

    @Override
    public String toString() {
        return "ProjectFlowsVo{" +
                "project='" + project + '\'' +
                ", projectId=" + projectId +
                ", flows=" + Arrays.toString(flows) +
                '}';
    }
}
```

**Json String**

```
{
  "flows" : [ {
    "flowId" : "29359de51f8b4d358e15b734c3f8167f"
  }, {
    "flowId" : "task_25_prod"
  } ],
  "project" : "task_25_prod",
  "projectId" : 288
}
```

**StackTrace Log**

```
2020-07-07 16:06:42.257  INFO 3041 --- [io-8994-exec-23] q.d.s.d.s.i.AzkabanDispatcherServiceImpl : execute result = {
  "flows" : [ {
    "flowId" : "29359de51f8b4d358e15b734c3f8167f"
  }, {
    "flowId" : "task_25_prod"
  } ],
  "project" : "task_25_prod",
  "projectId" : 288
}
2020-07-07 16:06:42.257  INFO 3041 --- [io-8994-exec-23] q.d.s.d.s.i.AzkabanDispatcherServiceImpl : execute end, elapsed = 4081
2020-07-07 16:09:45.561 ERROR 3041 --- [io-8994-exec-23] q.d.s.d.s.i.AzkabanDispatcherServiceImpl : execute throw exception

java.lang.IllegalAccessError: com/google/gson/internal/$Gson$Types$GenericArrayTypeImpl
        at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:106) ~[gson-2.8.6.jar!/:na]
        at com.google.gson.reflect.TypeToken.<init>(TypeToken.java:72) ~[gson-2.8.6.jar!/:na]
        at com.google.gson.reflect.TypeToken.get(TypeToken.java:296) ~[gson-2.8.6.jar!/:na]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:167) ~[gson-2.8.6.jar!/:na]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102) ~[gson-2.8.6.jar!/:na]
        at com.google.gson.Gson.getAdapter(Gson.java:458) ~[gson-2.8.6.jar!/:na]
        at com.google.gson.Gson.fromJson(Gson.java:931) ~[gson-2.8.6.jar!/:na]
        at com.google.gson.Gson.fromJson(Gson.java:897) ~[gson-2.8.6.jar!/:na]
        at com.google.gson.Gson.fromJson(Gson.java:846) ~[gson-2.8.6.jar!/:na]
        at com.google.gson.Gson.fromJson(Gson.java:817) ~[gson-2.8.6.jar!/:na]
        at com.qihoo.dw.stark.dispatcher.service.impl.AzkabanDispatcherServiceImpl.execute(AzkabanDispatcherServiceImpl.java:377) [stark-dispatcher-1.0.jar!/:na]
        at com.qihoo.dw.stark.dispatcher.service.impl.AzkabanDispatcherServiceImpl.fetchProjectFlows(AzkabanDispatcherServiceImpl.java:129) [stark-dispatcher-1.0.jar!/:na]
        at com.qihoo.dw.biz.task.impl.TaskExecServiceImpl.execTask(TaskExecServiceImpl.java:142) [classes!/:na]
        at com.qihoo.dw.web.task.TaskExecController.submitTaskExec(TaskExecController.java:70) [classes!/:na]
        at sun.reflect.GeneratedMethodAccessor908.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_221]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_221]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) [spring-web-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) [spring-web-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116) [spring-webmvc-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) [spring-webmvc-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) [spring-webmvc-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) [spring-webmvc-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963) [spring-webmvc-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897) [spring-webmvc-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [spring-webmvc-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872) [spring-webmvc-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:648) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [spring-webmvc-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.5.11.jar!/:8.5.11]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55) [spring-boot-1.5.2.RELEASE.jar!/:1.5.2.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:108) [spring-boot-actuator-1.5.2.RELEASE.jar!/:1.5.2.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105) [spring-web-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81) [spring-web-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) [spring-web-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106) [spring-boot-actuator-1.5.2.RELEASE.jar!/:1.5.2.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_221]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_221]

2020-07-07 16:10:00.051 DEBUG 3041 --- [pool-1-thread-1] c.q.d.d.m.D.countAllDataSet              : ==>  Preparing: select count(distinct dataset_id) from dw_dataset
```

**Comment by Hanry0204** [comment] 2020-07-08 03:47
The error is thrown when $Gson$Types.canonicalize in TypeToken.get(fieldType). The service starts in server mode，will it be due to a problem with this setting in -server mode?

**Comment by Marcono1234** [comment] 2020-07-10 18:52
This is rather weird, `$Gson$Types.canonicalize` should have access to `$Gson$Types$GenericArrayTypeImpl` since it is declared in the same class. Do you possibly have custom class loaders in place which could be causing this?

**Comment by Hanry0204** [comment] 2020-07-13 06:48
> This is rather weird, `$Gson$Types.canonicalize` should have access to `$Gson$Types$GenericArrayTypeImpl` since it is declared in the same class. Do you possibly have custom class loaders in place which could be causing this (or maybe it is caused by Spring's class loaders)?


I don’t have a custom classLoader. I use the spring boot framework. When the program throws an exception, I remotely debug and find that the typeTokenCache variable does not have the TypeToken required by the class above. When re-acquiring the Type Adapter, IllegalAccessError was thrown in getBoundFields of ReflectiveTypeAdapterFactory. It is not clear why the typeTokenCache does not have the TypeToken loaded when the program starts

**Comment by joe-szmn** [comment] 2020-07-17 08:36
i got following error:
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.IllegalAccessError: com/google/gson/internal/$Gson$Types$ParameterizedTypeImpl
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:982) ~[spring-webmvc-4.3.25.RELEASE.jar:4.3.25.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) ~[spring-webmvc-4.3.25.RELEASE.jar:4.3.25.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.25.RELEASE.jar:4.3.25.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api-3.1.0.jar:3.1.0]
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74) ~[undertow-servlet-2.0.28.Final.jar:2.0.28.Final]

**Comment by Marcono1234** [comment] 2022-08-12 12:30
If you are still experiencing this, could you please create a small self-contained Maven or Gradle project showing this issue (if necessary also with intructions for how to reproduce this)?

**Comment by Marcono1234** [comment] 2024-02-03 15:55
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.

**Closed by Marcono1234** 2024-02-03 15:55 UTC
Labels: bug, needs-info
