### ISSUE TITLE
Gson.toJson problem with Map when Map is initialised with double brace

### ISSUE THREAD

**Issue by wargun02** [google/gson#861] opened 2016-05-21 04:43 UTC
I've discovered that Gson could not serialize a Map to json if the Map is initialized in the double brace way.

I'm running on:
Mac OSX El Capitan
Gson 2.6.2
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)

Steps to reproduce, just run the following and you'll see the result:
```java
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import java.util.HashMap;
import java.util.Map;

public class GsonTest {

    public static void main( String[] args ) {
        Map<String, String> map1 = new HashMap();
        map1.put( "test", "123" );

        Map<String, String> map2 = new HashMap() {
            {
                put( "test", "123" );
            }
        };

        Gson gson = new GsonBuilder().create();
        System.out.println( gson.toJson( map1 ) );    // Will print correctly
        System.out.println( gson.toJson( map2 ) );    // Will only print null
    }
}
```

**Comment by JakeWharton** [comment] 2016-05-21 04:45
Dupe of #762. Please see reasoning (and workaround) there.

**Closed by JakeWharton** 2016-05-21 04:45 UTC

**Comment by wargun02** [comment] 2016-05-21 04:59
Thanks for the pointers.
