### ISSUE TITLE
DefaultDateTypeAdapter does not serialize null values

### ISSUE THREAD

**Issue by kbudaeus** [google/gson#1120] opened 2017-07-19 12:43 UTC
The following code gives a NPE:

```
class WrapperObject {
        Date date = null;
        WrapperObject() {};
    }
        
Gson parser = new GsonBuilder().serializeNulls().setDateFormat(DateFormat.LONG, DateFormat.LONG).create();
WrapperObject wrapper = new WrapperObject();
String jsonString = parser.toJson(wrapper);
System.out.println(jsonString);
```

With the following stack trace:

```
        java.lang.NullPointerException
	at java.util.Calendar.setTime(Calendar.java:1770)
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:943)
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:936)
	at java.text.DateFormat.format(DateFormat.java:345)
	at com.google.gson.DefaultDateTypeAdapter.write(DefaultDateTypeAdapter.java:88)
	at com.google.gson.DefaultDateTypeAdapter.write(DefaultDateTypeAdapter.java:40)
```

The DefaultDateTypeAdapter should handle null values. E.g.:

```
    public void write(JsonWriter out, Date value) throws IOException {
        synchronized (localFormat) {
            // Fix to deal with null values.
            if (value == null) {
                out.nullValue();
            }
            else {
                String dateFormatAsString = enUsFormat.format(value);
                out.value(dateFormatAsString);
            }
        }
    }
```

**Comment by JakeWharton** [comment] 2017-07-19 13:38
Dupe of #1096

**Closed by JakeWharton** 2017-07-19 13:38 UTC
