### ISSUE TITLE
GSON error in HTC Explorer

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#517] opened 2015-03-19 18:33 UTC
```
What steps will reproduce the problem?
1. Just try the follow sentence: gson.fromJson(string, Object.class); The 
string (is an object saved correctly before).
2.
3.

What is the expected output? What do you see instead?
I'd like to have the store object. I recevied the follow error: No-args 
constructor for class does not exist. Register an InstanceCreator with Gson for 
this type to fix this problem.

What version of the product are you using? On what operating system?
Android HTC Explorer in version 2.3.3

Please provide any additional information below.
Currently I'm working in a project which is using GSON Library. The problems 
occurs when I run my application in HTC explorer. The GSON class constructor 
generate the follow exception:

No-args constructor for class does not exist. Register an InstanceCreator with 
Gson for this type to fix this problem.

I've tested the application in a lot of devices. In fact the application has a 
lot of downloads, and any one of them has any crash like this.

Any ideas? I've seen some other post but I couldn't fixed the bug.

Thanks in advance.
```

Original issue reported on code.google.com by `d...@clickless.es` on 25 May 2013 at 10:17

**Comment by Marcono1234** [comment] 2023-03-12 23:03
Going to close this since the issue is from 2013 and does not contain a complete example demonstrating the problem.

**Closed by Marcono1234** 2023-03-12 23:03 UTC
