### ISSUE TITLE
 Couldn't find com.google.gson.annotations.SerializedName.value

### ISSUE THREAD

**Issue by vaibhavjaiswal9** [google/gson#899] opened 2016-08-11 21:04 UTC
I am getting this crash.

Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:300)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.IncompatibleClassChangeError: Couldn't find com.google.gson.annotations.SerializedName.value
       at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:659)
       at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:641)
       at libcore.reflect.AnnotationAccess.getDeclaredAnnotation(AnnotationAccess.java:170)
       at java.lang.reflect.Field.getAnnotation(Field.java:242)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldName(ReflectiveTypeAdapterFactory.java:71)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldName(ReflectiveTypeAdapterFactory.java:67)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:142)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:83)
       at com.google.gson.Gson.getAdapter(Gson.java:359)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(ReflectiveTypeAdapterFactory.java:122)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.access$100(ReflectiveTypeAdapterFactory.java:46)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:92)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:91)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:142)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:83)
       at com.google.gson.Gson.getAdapter(Gson.java:359)
       at com.google.gson.Gson.fromJson(Gson.java:809)
       at com.google.gson.Gson.fromJson(Gson.java:775)
       at com.google.gson.Gson.fromJson(Gson.java:724)
       at com.google.gson.Gson.fromJson(Gson.java:696)

**Comment by JakeWharton** [comment] 2016-08-11 21:11
Dupe of #726. This isn't caused by Gson, but by the (likely broken) OS the phone is using.

**Closed by JakeWharton** 2016-08-11 21:11 UTC

**Comment by vaibhavjaiswal9** [comment] 2016-08-11 21:53
Can u pls assist me how to resolve it??

Thanks.

**Comment by bhavenshahoptimumbrew** [comment] 2019-06-11 04:43
Yes this happens in most of Samsung phones. I also got same issue.

I got the solution of it. 

At first all phone's company ignoring comments ( //  or  /* */ ) in .json File.

But now Samsung developers are not ignoring it. 

So The best Solution is that you have to remove all comments ( // or /* */ ) in your .json file
