### ISSUE TITLE
Stackoverflow error but no circular references

### ISSUE THREAD

**Issue by MaryCooperGD** [google/gson#1514] opened 2019-04-16 15:43 UTC
I know this is a problem seen millions of time and everytime the cause was circular reference, but in my case I can't really find where it could be, since what it's serialized/deserialized are Strings. The specific error is this:

```
2019-04-16 16:32:16.843 ERROR 7452 --- [nio-9090-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.StackOverflowError] with root cause

java.lang.StackOverflowError: null
    at java.base/java.nio.CharBuffer.<init>(CharBuffer.java:281) ~[na:na]
    at java.base/java.nio.HeapCharBuffer.<init>(HeapCharBuffer.java:75) ~[na:na]
    at java.base/java.nio.CharBuffer.wrap(CharBuffer.java:393) ~[na:na]
    at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:280) ~[na:na]
    at java.base/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125) ~[na:na]
    at java.base/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:135) ~[na:na]
    at java.base/java.io.OutputStreamWriter.write(OutputStreamWriter.java:229) ~[na:na]
    at java.base/java.io.Writer.write(Writer.java:249) ~[na:na]
    at com.google.gson.stream.JsonWriter.string(JsonWriter.java:566) ~[gson-2.8.5.jar:na]
    at com.google.gson.stream.JsonWriter.writeDeferredName(JsonWriter.java:402) ~[gson-2.8.5.jar:na]
    at com.google.gson.stream.JsonWriter.value(JsonWriter.java:417) ~[gson-2.8.5.jar:na]
    at com.google.gson.internal.bind.TypeAdapters$16.write(TypeAdapters.java:406) ~[gson-2.8.5.jar:na]
    at com.google.gson.internal.bind.TypeAdapters$16.write(TypeAdapters.java:390) ~[gson-2.8.5.jar:na]
    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[gson-2.8.5.jar:na]
[...]
```

My method is this:

```
@PostMapping(path = PathConstants.START_ACTION)
	public ResponseEntity<BaseResponse<ProcessInstance>> start(@PathVariable String processDefinitionId,
			@RequestBody(required = false) Map<String, Object> params) {

		LOGGER.info("starting process definition with id {}", processDefinitionId);
		
		Map<String, Object> variables;
		ResponseEntity<BaseResponse<ProcessInstance>> response = null;
		PrintStream o = null;
		try {
			o = new PrintStream(new File("output.txt"));
		} catch (FileNotFoundException e1) {
			e1.printStackTrace();
		}
		System.setOut(o);
		ProcessInstance pi = null;
		LocalDateTime time = LocalDateTime.now();
		try {
			if (params != null) {			
				pi = runtimeService.startProcessInstanceById(processDefinitionId, params);			
			} else {
				System.out.println("Empty ");
				pi = runtimeService.startProcessInstanceById(processDefinitionId);
			}

			response = new ResponseEntity<>(new BaseResponse<>(Constants.OK, pi), HttpStatus.OK);
			
			if(pi.isEnded()) {		
				HistoricProcessInstance hpi = historyService.createHistoricProcessInstanceQuery().includeProcessVariables().
						processInstanceId(pi.getId()).singleResult();
				variables = hpi.getProcessVariables();
				System.out.println("Variables " + variables);
				if(variables.get("result").equals("OK")) {
					MongoOperations.writeLogSuccess(pi, pi.getProcessDefinitionName());
				} else {
					MongoOperations.writeLogFailure(hpi.getDurationInMillis(), hpi.getStartTime(), pi.getProcessDefinitionName());
				}
			}
			else {
				variables =  runtimeService.getVariables(pi.getId());
			}
		} catch (FlowableObjectNotFoundException e) {
			String pdn = repositoryService.getProcessDefinition(processDefinitionId).getName();
			MongoOperations.writeLogException(time, pdn);
			response = new ResponseEntity<>(new BaseResponse<>(e.getMessage(), null), HttpStatus.NOT_FOUND);
		} catch (FlowableException e) { 
			String pdn = repositoryService.getProcessDefinition(processDefinitionId).getName();
			MongoOperations.writeLogException(time, pdn);
			response = new ResponseEntity<>(new BaseResponse<>(e.getMessage(), null), HttpStatus.INTERNAL_SERVER_ERROR); // other exception are managed here
		} catch (Exception e) {
			String pdn = repositoryService.getProcessDefinition(processDefinitionId).getName();
			MongoOperations.writeLogException(time, pdn);
			response = new ResponseEntity<>(new BaseResponse<>(e.getMessage(), null), HttpStatus.INTERNAL_SERVER_ERROR); // other exception are managed here
		}
		return response;
	}
```
Basically what I'm doing is retrieving this Map passed as body, that is a simple json String: 

```
{
    "name": "morpheus",
    "job": "leader"
}
```
This is passed as body in postman. Since never in my method I call a `toJson()` function, the error must be when the Map is retrieved by my method. In fact, if I call the method without body (that is optional), the error is not thrown.    
But where is the error? I'm working with Strings and not with custom Objects that have some strange loops or back/forward references to themselves, so what is the cause?

**Comment by MedMaalej** [comment] 2019-04-20 19:23
> I know this is a problem seen millions of time and everytime the cause was circular reference, but in my case I can't really find where it could be, since what it's serialized/deserialized are Strings. The specific error is this:
> 
> ```
> 2019-04-16 16:32:16.843 ERROR 7452 --- [nio-9090-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.StackOverflowError] with root cause
> 
> java.lang.StackOverflowError: null
>     at java.base/java.nio.CharBuffer.<init>(CharBuffer.java:281) ~[na:na]
>     at java.base/java.nio.HeapCharBuffer.<init>(HeapCharBuffer.java:75) ~[na:na]
>     at java.base/java.nio.CharBuffer.wrap(CharBuffer.java:393) ~[na:na]
>     at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:280) ~[na:na]
>     at java.base/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125) ~[na:na]
>     at java.base/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:135) ~[na:na]
>     at java.base/java.io.OutputStreamWriter.write(OutputStreamWriter.java:229) ~[na:na]
>     at java.base/java.io.Writer.write(Writer.java:249) ~[na:na]
>     at com.google.gson.stream.JsonWriter.string(JsonWriter.java:566) ~[gson-2.8.5.jar:na]
>     at com.google.gson.stream.JsonWriter.writeDeferredName(JsonWriter.java:402) ~[gson-2.8.5.jar:na]
>     at com.google.gson.stream.JsonWriter.value(JsonWriter.java:417) ~[gson-2.8.5.jar:na]
>     at com.google.gson.internal.bind.TypeAdapters$16.write(TypeAdapters.java:406) ~[gson-2.8.5.jar:na]
>     at com.google.gson.internal.bind.TypeAdapters$16.write(TypeAdapters.java:390) ~[gson-2.8.5.jar:na]
>     at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[gson-2.8.5.jar:na]
> [...]
> ```
> My method is this:
> 
> ```
> @PostMapping(path = PathConstants.START_ACTION)
> 	public ResponseEntity<BaseResponse<ProcessInstance>> start(@PathVariable String processDefinitionId,
> 			@RequestBody(required = false) Map<String, Object> params) {
> 
> 		LOGGER.info("starting process definition with id {}", processDefinitionId);
> 		
> 		Map<String, Object> variables;
> 		ResponseEntity<BaseResponse<ProcessInstance>> response = null;
> 		PrintStream o = null;
> 		try {
> 			o = new PrintStream(new File("output.txt"));
> 		} catch (FileNotFoundException e1) {
> 			e1.printStackTrace();
> 		}
> 		System.setOut(o);
> 		ProcessInstance pi = null;
> 		LocalDateTime time = LocalDateTime.now();
> 		try {
> 			if (params != null) {			
> 				pi = runtimeService.startProcessInstanceById(processDefinitionId, params);			
> 			} else {
> 				System.out.println("Empty ");
> 				pi = runtimeService.startProcessInstanceById(processDefinitionId);
> 			}
> 
> 			response = new ResponseEntity<>(new BaseResponse<>(Constants.OK, pi), HttpStatus.OK);
> 			
> 			if(pi.isEnded()) {		
> 				HistoricProcessInstance hpi = historyService.createHistoricProcessInstanceQuery().includeProcessVariables().
> 						processInstanceId(pi.getId()).singleResult();
> 				variables = hpi.getProcessVariables();
> 				System.out.println("Variables " + variables);
> 				if(variables.get("result").equals("OK")) {
> 					MongoOperations.writeLogSuccess(pi, pi.getProcessDefinitionName());
> 				} else {
> 					MongoOperations.writeLogFailure(hpi.getDurationInMillis(), hpi.getStartTime(), pi.getProcessDefinitionName());
> 				}
> 			}
> 			else {
> 				variables =  runtimeService.getVariables(pi.getId());
> 			}
> 		} catch (FlowableObjectNotFoundException e) {
> 			String pdn = repositoryService.getProcessDefinition(processDefinitionId).getName();
> 			MongoOperations.writeLogException(time, pdn);
> 			response = new ResponseEntity<>(new BaseResponse<>(e.getMessage(), null), HttpStatus.NOT_FOUND);
> 		} catch (FlowableException e) { 
> 			String pdn = repositoryService.getProcessDefinition(processDefinitionId).getName();
> 			MongoOperations.writeLogException(time, pdn);
> 			response = new ResponseEntity<>(new BaseResponse<>(e.getMessage(), null), HttpStatus.INTERNAL_SERVER_ERROR); // other exception are managed here
> 		} catch (Exception e) {
> 			String pdn = repositoryService.getProcessDefinition(processDefinitionId).getName();
> 			MongoOperations.writeLogException(time, pdn);
> 			response = new ResponseEntity<>(new BaseResponse<>(e.getMessage(), null), HttpStatus.INTERNAL_SERVER_ERROR); // other exception are managed here
> 		}
> 		return response;
> 	}
> ```
> Basically what I'm doing is retrieving this Map passed as body, that is a simple json String:
> 
> ```
> {
>     "name": "morpheus",
>     "job": "leader"
> }
> ```
> This is passed as body in postman. Since never in my method I call a `toJson()` function, the error must be when the Map is retrieved by my method. In fact, if I call the method without body (that is optional), the error is not thrown.
> But where is the error? I'm working with Strings and not with custom Objects that have some strange loops or back/forward references to themselves, so what is the cause?

Obviously, the error is not related to the map you passed as argument. The problem is for sure with the processing you did inside the "start" method. I suggest that you check your Json objects hierarchy/references (for all the objects you used inside the "start" method)

**Comment by Marcono1234** [comment] 2024-01-07 22:55
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.

**Closed by Marcono1234** 2024-01-07 22:55 UTC
Labels: needs-info
