### ISSUE TITLE
From Gson returns null object

### ISSUE THREAD

**Issue by muneebqadir** [google/gson#1871] opened 2021-03-04 01:49 UTC
I am coverting this class from JSON string but gson is returning null

```
public class Service {
    public String ServiceName;
    public ArrayList<String> ParamList;
    public ArrayList<String> ParamType;

    public Service(String sn,ArrayList<String> pl,ArrayList<String> pt) {
        this.ServiceName = sn;
        this.ParamList = pl;
        this.ParamType = pt;
        // TODO Auto-generated constructor stub
    }

```

This is the String that needs to be parsed
`{"ParamList":[],"ParamType":[],"ServiceName":"ServiceX"}
`
Android code:
`gson.fromJson(response,Client.Service.class)`

**Comment by lyubomyr-shaydariv** [comment] 2021-03-04 10:40
`Client.Service.class` looks like a non-static inner/nested class. Make it `static` as it is also suggested in [your cross-posted question](https://stackoverflow.com/questions/66467196/json-always-returns-null-when-parsing-into-pojo-with-gson) or put the `Service` class to the package not a part of the `Client` class. Additionally, accept the [answer](https://stackoverflow.com/questions/66467196/json-always-returns-null-when-parsing-into-pojo-with-gson/66468541#66468541) as it tells a right thing (I suspect you're missing the `static` keyword in the 6-hrs-old answer though since the user spent their time to help you out despite not knowing the specifics but receiving zero feedback from you (start-reputation users can't vote at S.O.)), and close this one as it is not a bug or an issue.

**Comment by Marcono1234** [comment] 2022-08-12 12:11
Closing this because you [commented on your StackOverflow question](https://stackoverflow.com/questions/66467196/json-always-returns-null-when-parsing-into-pojo-with-gson#comment117514852_66468541):
> It was an environment issue on Android Studio. Re-built the project and added dependencies again and it worked

**Closed by Marcono1234** 2022-08-12 12:11 UTC
