### ISSUE TITLE
Gson 2.8.1 DefaultDateTypeAdapter is not null safe.

### ISSUE THREAD

**Issue by NightlyNexus** [google/gson#1098] opened 2017-06-06 19:11 UTC
```java
public void testNullSafe() throws IOException {
  TypeAdapter<Date> date =
    new GsonBuilder().setDateFormat("yyyy-MM-dd HH:mm:ss Z").create().getAdapter(Date.class);
  assertNull(date.fromJson("null"));
}
```
fails.
The recent change to the streaming adapter unfortunately broke some backwards compatibility for some of my projects.

**Comment by JakeWharton** [comment] 2017-07-19 13:37
Dupe of #1096

**Closed by JakeWharton** 2017-07-19 13:37 UTC
