### ISSUE TITLE
2.8.6 Throws exception （Cause: zip file is empty） when building with Android Studio 

### ISSUE THREAD

**Issue by jaydroid1024** [google/gson#1683] opened 2020-04-20 10:10 UTC
Execution failed for task ':boss:transformClassesWithDexBuilderForDebug'.
com.android.build.api.transform.TransformException: java.util.zip.ZipException: zip file is empty
2.8.5 is ok

These are the relevant build information I checked, but I'm not sure if it's my problem
`AGPBI: {"kind":"error","text":"Zip error while reading '/Users/xuejiewang/AndroidStudioProjects/QLife/package_name_XXX/XXX/build/intermediates/transforms/ajx/debug/**217.jar**': zip file is empty","sources":[{}],"tool":"D8"}
`

`{
	"name": "com.google.code.gson:gson:2.8.6_fb48d0051ec11deca68ca08fb0cdfb54",
	"index": 217,
	"scopes": ["EXTERNAL_LIBRARIES"],
	"types": ["CLASSES"],
	"format": "JAR",
	"present": true
}`

**Comment by wancong3** [comment] 2020-05-02 15:45
Yes, 2.8.6 has some bugs in android.

**Comment by ganeshpadhayay** [comment] 2020-10-30 05:29
I am facing this in 2.8.5 also, Did someone find a solution for this? I am stuck on this for days now.

**Comment by Marcono1234** [comment] 2022-08-12 12:37
Could you please try if this still occurs with the latest Gson version? Also try to update the build tools and plugins you are using.

**Comment by Marcono1234** [comment] 2024-01-07 22:54
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.

**Closed by Marcono1234** 2024-01-07 22:54 UTC
Labels: needs-info

**Comment by PVPliangzhen** [comment] 2024-10-08 08:41
your details is enough, but nobody resolved

**Comment by Marcono1234** [comment] 2024-10-08 21:26
@PVPliangzhen, what do you mean by that? Are you experiencing this issue? If so please mention which Gson version and build tools you are using (ideally try the latest versions), and if possible provide a small complete sample project for reproducing this. Just based on the details provided by the original reporter it is difficult to understand what is causing this and how it can be solved.

Gson 2.8.6 had included the `module-info.class` file in the root directory of the JAR, which caused issues for build tools, especially for Android. That has been solved in newer Gson versions (see #2013), and also Android and other build tools have improved handling for `module-info.class`.

That is why I asked if this is actually still a problem with the latest Gson version and build tool versions, because most likely this has already been solved.
