### ISSUE TITLE
Stackoverflow recursive call but only on certain builds

### ISSUE THREAD

**Issue by ncapdevi** [google/gson#1085] opened 2017-05-24 20:16 UTC
```
 ERR: stack=java.lang.StackOverflowError: stack size 8MB
                                                       at com.google.gson.internal.$Gson$Types.checkNotPrimitive($Gson$Types.java:434)
                                                       at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:544)
                                                       at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:111)
                                                       at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:553)
                                                       at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:111)
                                                       at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:546)
                                                       at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:111)
                                                       at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:553)
                                                       at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:111)
                                                       at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:546)
                                                       at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:111)
                                                       at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:553)
                                                       at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:111)
                                                       at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:546)
                                                       at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:111)
                                                       at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:553)
                                                       at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:111)
                                                       at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:546)
                                                       at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:111)
                                                       at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:553)
                                                       at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:111)
                                                       at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:546)
                                                       at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:111)
                                                       at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:553)
                                                       at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:111)
                                                       at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:546)
                                                       at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:111)
                                                       at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:553)
                                                       at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:111)
                                                       at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:546)
                                                       at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:111)
                                                       at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:553)
                                                       at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:111)
                                                       at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:546)
                                                       at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:111)
                                                       at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:553)
                                                       at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:111)
                                                       at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:546)
                                                       at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:111)
                                                       at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:553)
                                                       at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:111)
                                                       at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:546)
                                                       at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:111)
                                                       at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:553)
                                                       at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:111)
                                                       at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:546)
                                                       at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:111)
                                                       at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:553)
                                                       at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:111)
                                                   	at com.google.gson
```

This error just started recently occuring, but only on certain builds. If I'm building for the latest preview of Android O Dev Preview 2, it works fine, but if I build it and run the APK on a Samsung S5 on 6.0.1, this error occurs.

**Comment by Marcono1234** [comment] 2022-09-10 21:27
Looks like a duplicate of #597

**Closed by Marcono1234** 2022-09-10 21:27 UTC
