### ISSUE TITLE
Smart quotes are treated incorrectly

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#598] opened 2015-03-19 18:34 UTC
```
What steps will reproduce the problem?
1. Create a string that uses smart quotes around the key or value or both in a 
JSON element
2. Have GSON parse it into a map
3. Have GSON turn it back into JSON

What is the expected output? What do you see instead?
GSON treats the smart quotes as part of the key or value.  GSON should not 
consider this valid JSON at all.  Jsonlint.com does not, Chrome does not.

Please provide any additional information below.

In Java use a string like this:

private static final String badJson = " { “ipAddress” : “192.168.1.100” 
}";

Smart quotes are sround ipAddress and 192.168.1.100, those are not regular 
quotes.

Then do this:

Gson gson = new Gson();
Map<String, String> map;
map = gson.fromJson(json, Map.class);
System.out.println(name + gson.toJson(map));

Gson will print this:

{"“ipAddress”":"“192.168.1.100”"}
```

Original issue reported on code.google.com by `t...@mattison.org` on 19 Sep 2014 at 10:53

**Comment by paulrutter** [comment] 2016-08-30 07:37
Any update on this issue?

**Comment by swankjesse** [comment] 2016-08-30 11:24
The problem is that Gson.fromJson() is lenient by default. Work around this by getting the type adapter from the Gson instance and using it to call fromJson.

**Comment by camdenorrb** [comment] 2016-09-14 03:34
I have been experiencing the same issue. Vouch.

**Comment by Marcono1234** [comment] 2024-05-20 22:30
I am going to close this because no answer has been provided.

Note that in Gson version 2.11.0 a new `Strictness` API was added, so you can for example use [`gsonBuilder.setStrictness(Strictness.STRICT)`](https://www.javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/GsonBuilder.html#setStrictness(com.google.gson.Strictness)) to override the default lenient behavior (which allows these 'smart quotes').

Feel free to comment here again or create a new Issue or Discussion if anything is unclear or if you think there might be a better solution.

**Closed by Marcono1234** 2024-05-20 22:30 UTC
