### ISSUE TITLE
parse bug(json syntax error but parse success..)

### ISSUE THREAD

**Issue by ruinnel** [google/gson#808] opened 2016-03-08 01:15 UTC
this is my code..

```
public static final void main(String[] args) {
    String params = "{\"menu\":0,\"level\":0,\"curMon\":2,\"curDay\":29,\"curHour\":9,\"curMin\":30,\"curIsAm\":true,\"rsvMon\":2,\"rsvDay\":29,\"rsvHour\":11\",rsvMin\":30,\"rsvIsAm\":true}";
    Gson gson = new GsonBuilder().create();
    Type type = new TypeToken<Map<String, Object>>() {}.getType();
    Map<String, Object> parsedParams = gson.fromJson(params, type);

    System.out.println(gson.toJson(parsedParams));
  }
```

source json is....
{"menu":0,"level":0,"curMon":2,"curDay":29,"curHour":9,"curMin":30,"curIsAm":true,"rsvMon":2,"rsvDay":29,**"rsvHour":11",rsvMin":30,**"rsvIsAm":true}

and after parsed..
 {"menu":0.0,"level":0.0,"curMon":2.0,"curDay":29.0,"curHour":9.0,"curMin":30.0,"curIsAm":true,"rsvMon":2.0,"rsvDay":29.0,"**rsvHour":"11\"","rsvMin\"":30.0**,"rsvIsAm":true}

**Comment by Marcono1234** [comment] 2023-03-12 23:02
Gson's JSON parsing is lenient by default (see also #372). You can however work around this, see the "Lenient JSON handling" section of the [`Gson` class documentation](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/Gson.html).

I am going to close this issue since the problem is already tracked by other GitHub issues.

**Closed by Marcono1234** 2023-03-12 23:02 UTC
