### ISSUE TITLE
StackOverflow when use JsonObject and  JsonArray.

### ISSUE THREAD

**Issue by broken1arrow** [google/gson#2035] opened 2021-12-19 14:39 UTC
# Gson version
2.8.9

# Java / Android version
java 16 or java 11

# Used tools

- [x] Maven; version: 3.8.1

# Description

I´m not an expert and docs is not clear. But I have always have option in normal java add list/arraylist inside a map.

So i do like i always doo (when need add array inside a map or in this case json). and not use deepCopy() (You should have option to get the elements with out need copy it extra time (the only thing it do is loop thru all contents an extra time)). 
		
````
                      JsonObject json = new JsonObject();
                      JsonArray jsonarray = new JsonArray();
                     json.add("color","some other value")
                   json.add("text","some other value")
                    JsonObject jsonObject = new JsonObject();
			jsonObject.add("extra", jsonarray); 
````

## Expected behavior
should not give 
java.lang.StackOverflowError: null

## Actual behavior

give this error if i not add deepCopy().
java.lang.StackOverflowError: null

# Reproduction steps

only a test 
		
````
                      JsonObject json = new JsonObject();
                      JsonArray jsonarray = new JsonArray();
                     json.add("color","some other value")
                   json.add("text","some other value")
                    JsonObject jsonObject = new JsonObject();
			jsonObject.add("extra", jsonarray); 
````

# Exception stack trace

this is only for 2 object inside the array.
https://pastebin.com/vZzNgLnc

**Comment by abimarank** [comment] 2021-12-20 14:54
Can you add the sample code here?

**Comment by broken1arrow** [comment] 2021-12-20 16:04
> Can you add the sample code here?

So better an the code example i give?

This is a example some will give errors. If i not add deepCopy(). 
````
		public void someCode() {
			JsonObject json = new JsonObject();

			json.addProperty("color", "some value");
			json.addProperty("text", "some value");
			
			JsonArray jsonarray = new JsonArray();
			JsonObject jsonObject = new JsonObject();
			jsonarray.add(json);
			
			jsonObject.add("extra", jsonarray);
		}

```

**Comment by broken1arrow** [comment] 2021-12-20 16:16
I´m confused. When I write this yesterday. I get the bug constantly. But now seams it to work. I will do more testings, because it is very strange.

**Comment by Marcono1234** [comment] 2021-12-21 18:25
Are you sure that you are using Gson version 2.8.9? The line numbers in the stack trace look a lot like version 2.8.8.

Could it be that by accident you created a cyclic data structure, for example a JSON object containing a JSON array containing the previous JSON object? The Gson version 2.8.8 line numbers seem to indicate that repeatedly a JSON array element is written ([here](https://github.com/google/gson/blob/b41030d3dc965eca1b0a0f1c35ce185dd8e80e99/gson/src/main/java/com/google/gson/internal/bind/TypeAdapters.java#L755)) and a JSON object property ([here](https://github.com/google/gson/blob/b41030d3dc965eca1b0a0f1c35ce185dd8e80e99/gson/src/main/java/com/google/gson/internal/bind/TypeAdapters.java#L763)).

**Comment by broken1arrow** [comment] 2021-12-21 19:11
> Are you sure that you are using Gson version 2.8.9? The line numbers in the stack trace look a lot like version 2.8.8.
> 
> Could it be that by accident you created a cyclic data structure, for example a JSON object containing a JSON array containing the previous JSON object? The Gson version 2.8.8 line numbers seem to indicate that repeatedly a JSON array element is written ([here](https://github.com/google/gson/blob/b41030d3dc965eca1b0a0f1c35ce185dd8e80e99/gson/src/main/java/com/google/gson/internal/bind/TypeAdapters.java#L755)) and a JSON object property ([here](https://github.com/google/gson/blob/b41030d3dc965eca1b0a0f1c35ce185dd8e80e99/gson/src/main/java/com/google/gson/internal/bind/TypeAdapters.java#L763)).

If I use 2.8.8 is maven fault, because I set it to use 2.8.9.

**Comment by Marcono1234** [comment] 2021-12-23 00:30
>"repeatedly a JSON array element is written"
is the strange part, because only call the code 1 time.

What I meant is that Gson is repeatedly writing the data. Even though you only call the Gson method once, because there is a cyclic data structure, Gson gets into an endless recursive loop, which eventually leads to a `StackOverflowError`.

**Comment by broken1arrow** [comment] 2021-12-23 08:51
> > "repeatedly a JSON array element is written"
> > is the strange part, because only call the code 1 time.
> 
> What I meant is that Gson is repeatedly writing the data. Even though you only call the Gson method once, because there is a cyclic data structure, Gson gets into an endless recursive loop, which eventually leads to a `StackOverflowError`.

yeah, I get it somehow get endless recursive loop. But should not happen with only two values.

I have not see the issue after I restart the computer. So maven perhaps use wrong version (even if i not import Gson inside maven before).

**Comment by eamonnmcmanus** [comment] 2021-12-24 01:24
I'm closing this for now, but if you are able to reproduce the problem feel free to reopen.

**Closed by eamonnmcmanus** 2021-12-24 01:24 UTC
Labels: bug
