### ISSUE TITLE
2.8.5；NullPointerException；TypeAdapterFactory

### ISSUE THREAD

**Issue by geolo123** [google/gson#1578] opened 2019-09-18 02:21 UTC
java.lang.NullPointerException: Attempt to invoke interface method 'com.google.gson.TypeAdapter com.google.gson.TypeAdapterFactory.create(com.google.gson.Gson, com.google.gson.reflect.TypeToken)' on a null object reference
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.Gson.fromJson(Gson.java:926)
	at com.google.gson.Gson.fromJson(Gson.java:892)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at com.google.gson.Gson.fromJson(Gson.java:813)

**Comment by geolo123** [comment] 2019-09-25 03:27
help

**Comment by Omega-Ariston** [comment] 2019-09-29 08:50
Please provide context and paste the code.

**Comment by aalaprawat** [comment] 2021-12-08 11:53
Iam not able to replicate this issue on my device. But various devices are facing this issue across various android api levels.

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'com.google.gson.TypeAdapter com.google.gson.TypeAdapterFactory.create(com.google.gson.Gson, com.google.gson.reflect.TypeToken)' on a null object reference
       at com.google.gson.Gson.getAdapter(Gson.java:458)
       at com.google.gson.Gson.toJson(Gson.java:696)
       at com.google.gson.Gson.toJson(Gson.java:683)
       at com.google.gson.Gson.toJson(Gson.java:638)
       at com.google.gson.Gson.toJson(Gson.java:618)
       at in.workindia.nileshdungarwal.helpers.JsonHelper.convertJobContentsToJson(JsonHelper.java:322)
       at in.workindia.nileshdungarwal.data_parser.ContentValuesParser.parseJobs(ContentValuesParser.java:335)
       at in.workindia.nileshdungarwal.data_parser.ContentValuesParser.parseNewJobs(ContentValuesParser.java:70)
       at in.workindia.nileshdungarwal.retrofit.RetrofitSyncAll.finalProcessOfJobs(RetrofitSyncAll.java:844)
       at in.workindia.nileshdungarwal.retrofit.RetrofitSyncAll$101.onResponse(RetrofitSyncAll.java:6591)
       at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0(DefaultCallAdapterFactory.java:81)
       at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:3)
       at retrofit2.-$$Lambda$DefaultCallAdapterFactory$ExecutorCallbackCall$1$hVGjmafRi6VitDIrPNdoFizVAdk.run(-.java:3)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8595)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)`

**Comment by Marcono1234** [comment] 2022-08-20 15:08
Unfortunately Gson does not check for `null` for the `GsonBuilder.registerTypeAdapterFactory` method. Could you please check whether by accident you are calling it with `null` as value?

**Comment by aalaprawat** [comment] 2022-08-22 06:00
@Marcono1234 

`gsonBuilder = new GsonBuilder();
        gsonBuilder.registerTypeAdapter(JsonNode.class, new JsonNodeSerializer());
        gsonBuilder.registerTypeAdapter(JsonNode.class, new JsonNodeDeserializer());
        Gson gson = gsonBuilder.create();`

I don't think this could be null

**Comment by Marcono1234** [comment] 2022-08-22 09:56
@aalaprawat, were you able to reproduce this locally with a debug build of your application as well? Could you please try to create a small self-contained sample project using the latest Gson version which shows this issue?

**Comment by aalaprawat** [comment] 2022-08-22 11:12
Currently, I am using Gson 2.8.6, would upgrading resolve the issue?
@Marcono1234

**Comment by Marcono1234** [comment] 2022-08-22 11:32
I am afraid using the latest version most likely does not make a big difference, but in case this is really a Gson bug it would avoid having to track down bugs in an old Gson version. Future Gson versions will also add validation for the `GsonBuilder` methods (#2179), maybe that would help track down the bug.

The stack trace suggests that somehow `null` was added as element to the `Gson.factories` list; but I don't see how that could have happened, other than by a call to `GsonBuilder.registerTypeAdapterFactory(null)`.

Since you mentioned it only occurs on some devices, maybe there is something wrong with those devices, or the Android version they are running.

**Comment by aalaprawat** [comment] 2022-08-22 11:45
facing issues across all the devices and API versions, As mentioned above through code snippet, I can't point where `GsonBuilder.registerTypeAdapterFactory(null)` could happen

**Comment by Marcono1234** [comment] 2024-02-03 16:02
Are you still experiencing this with the latest Gson version (currently 2.10.1)?

**Comment by Marcono1234** [comment] 2024-05-20 03:21
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.

**Closed by Marcono1234** 2024-05-20 03:21 UTC
Labels: needs-info
