### ISSUE TITLE
Using Gson with Proguard when Jack options are enabled(JAVA 8)

### ISSUE THREAD

**Issue by naveenthontepu** [google/gson#944] opened 2016-10-14 10:27 UTC
The Library used is gson:2.7 
Jack Options are enabled.
When running the apk with proguard with the Rules as 

`-keepattributes Signature`
`-keepattributes *Annotation*`
`-keep class sun.misc.Unsafe { *; }`
`#-keep class com.google.gson.stream.** { *; }`
`-keep class com.google.gson.examples.android.model.** { *; }`
`-keep class * implements com.google.gson.TypeAdapterFactory`
`-keep class * implements com.google.gson.JsonSerializer`
`-keep class * implements com.google.gson.JsonDeserializer`

The app is not even able to initialize a gson object using 

`Gson gson = new Gson();
`

The error is 
`
java.lang.RuntimeException: Missing type parameter.
`

**Comment by jamesrapadmi** [comment] 2019-06-05 14:32
Also have this issue

**Comment by Marcono1234** [comment] 2024-07-21 15:13
I am going to close this issue because it is quite old and there have been improvements for R8 and ProGuard handling in recent Gson versions.

If you still experience this with the latest Gson version, please create a new GitHub issue and provide a small self contained example for reproducing the issue.

**Closed by Marcono1234** 2024-07-21 15:13 UTC
