### ISSUE TITLE
Please log the name of property which can not be parse/read when using fromJson in the log/exception

### ISSUE THREAD

**Issue by binhjy** [google/gson#2184] opened 2022-08-25 05:29 UTC
Hi team,

Atm I'm using version 2.9.1, using fromJson as below to convert string to object
`public static <T> T jsonToObject(String json, Class<T> clazz) {
		return new Gson().fromJson(json, clazz);
	}`
But when one of 20 properties can not be parsed/read due to naming/object type, the log/exception is so not helpful, it does not log the field name
![image](https://user-images.githubusercontent.com/16265532/186581600-4c56c085-cbcc-44bb-8981-4bb47ed350ef.png)

Workaround is I have to debug at this class: ReflectiveTypeAdapterFactory, one by one property to know which one is wrong.
![image](https://user-images.githubusercontent.com/16265532/186581841-18f841e3-deeb-46bd-9b60-11b9206174fe.png)

So please help to log the property name before throw exception or include to the exception so that can quickly identify the wrong property.
Thanks

**Comment by Marcono1234** [comment] 2022-08-25 23:14
Is this only about the `NumberFormatException` shown in the stack trace (in that case this would be a duplicate of #1564), or did you notice that for other exceptions as well?

**Comment by binhjy** [comment] 2022-08-26 01:53
Hi @Marcono1234 , not only NumberFormatException , from what I've seen so far for all exceptions, for example in the input string, the property's value is json format but the dto just define String, so it can not be parse and will throw another exception (not NumberFormatException )

**Comment by Marcono1234** [comment] 2022-08-26 13:54
Could you please provide a concrete example for this? I think normally Gson would throw an `IllegalStateException` which properly describes where the exception occurred, for example:
```
IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 2 path $
```

**Comment by Marcono1234** [comment] 2024-02-03 16:09
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.

**Closed by Marcono1234** 2024-02-03 16:09 UTC
Labels: enhancement, needs-info
