### ISSUE TITLE
Create a GsonBuilder from Gson

### ISSUE THREAD

**Issue by kaqqao** [google/gson#1232] opened 2018-01-17 15:52 UTC
I'd like to request a feature that would allow obtaining a `GsonBuilder`instance from an existing `Gson` instance, similar to what Jackson enables via its `ObjectMapper#copy` method.

The rationale is that it would allow reusing existing configuration. E.g. frameworks often include a preconfigured `Gson`  instance and this way other libraries using Gson would be able to inherit the same configurations, but still override/add what they need.

**Comment by JakeWharton** [comment] 2018-01-17 15:53
Dupe of #1139 added by #1142.

**Closed by JakeWharton** 2018-01-17 15:53 UTC
