### ISSUE TITLE
Object to String return "null"

### ISSUE THREAD

**Issue by authorZhao** [google/gson#1795] opened 2020-10-09 08:51 UTC
version 2.8.5
```java
    private void sendFollowerActivity(){
@Data class ActivityPersonAuditResultDTO{private Long actId;private Integer auditStatus;}
        Long actId = 1906050000052709L;
        ActivityPersonAuditResultDTO dto = new ActivityPersonAuditResultDTO();
        dto.setActId(actId);
        dto.setAuditStatus(10);
        String gosn = new Gson().toJson(dto);//gosn is "null"
        String fastjson = JSON.toJSONString(dto); //fastjson is ok,{"actId":1906050000052709,"auditStatus":10}
}
```

**Comment by lyubomyr-shaydariv** [comment] 2020-10-10 18:26
Local classes are not supported. See #1510 and https://github.com/google/gson/blob/master/UserGuide.md#finer-points-with-objects .

**Comment by Marcono1234** [comment] 2022-08-12 12:23
Closing because as mentioned above the issue is that you are using local classes, and there are already other GitHub issues about this problem.

**Closed by Marcono1234** 2022-08-12 12:23 UTC
