### ISSUE TITLE
problem serializing null Date in version 2.8.1

### ISSUE THREAD

**Issue by chinhub2001** [google/gson#1157] opened 2017-09-15 10:14 UTC
Hello,

I was using gson 2.8.0 in my project and I had no problem at all, but after updating to 2.8.1 an exception is thrown serializing to json an object which has a null Date field.

this is the class code where the problem is:

```
public class CollectionAdapterGson implements JsonSerializer<Collection<?>> {

    @Override
    public JsonElement serialize(Collection<?> src, Type typeOfSrc, JsonSerializationContext context) {
        if (src == null || src.isEmpty()) // exclusion is made here
            return null;

        JsonArray array = new JsonArray();

        for (Object child : src) {
            JsonElement element = context.serialize(child);
            array.add(element);
        }

        return array;
    }
}
```

If the "child" object is something like this
```
class MyClass{
   Date myDate = null;
  ...
}
```

I've got following exception:
`java.lang.NullPointerException: Attempt to invoke virtual method 'long java.util.Date.getTime()' on a null object reference
                                                                  at java.util.Calendar.setTime(Calendar.java:1195)
                                                                  at java.text.SimpleDateFormat.formatImpl(SimpleDateFormat.java:518)
                                                                  at java.text.SimpleDateFormat.format(SimpleDateFormat.java:820)
                                                                  at java.text.DateFormat.format(DateFormat.java:314)
                                                                  at com.google.gson.DefaultDateTypeAdapter.write(DefaultDateTypeAdapter.java:88)
                                                                  at com.google.gson.DefaultDateTypeAdapter.write(DefaultDateTypeAdapter.java:40)
                                                                  at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
                                                                  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
                                                                  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
                                                                  at com.google.gson.Gson.toJson(Gson.java:669)
                                                                  at com.google.gson.Gson.toJsonTree(Gson.java:562)
                                                                  at com.google.gson.Gson.toJsonTree(Gson.java:541)
                                                                  at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155)
                                                                  at com.asdf.services.serialize.CollectionAdapterGson.serialize(CollectionAdapterGson.java:25)`

Any ideas what's going on?

Thanks!!!

**Comment by JakeWharton** [comment] 2017-09-15 13:35
Dupe of #1096

**Closed by JakeWharton** 2017-09-15 13:35 UTC
