### ISSUE TITLE
asMap() has to be called to serialize a multimap object

### ISSUE THREAD

**Issue by jimmyzzxhlh** [google/gson#1847] opened 2021-01-12 02:17 UTC
```
ArrayListMultimap<String, Integer> multimap = ArrayListMultimap.create();
multimap.put("1", 1);
multimap.put("1", 111);
multimap.put("2", 2);
System.out.println(gson.toJson(multimap));
```

This would print out a completely empty map, i.e. `{}`. 

If we call `System.out.println(gson.toJson(multimap.asMap()));` then it works, however this means that for any objects that have a Multimap property, the property will be serialized as an empty string when calling `toJson()`, which is very confusing. 

Edit: It is possible to resolve the issue by writing a custom type adaptor like the following. It'd be great if gson can just include a standard type adapter for Multimap. 
https://gist.github.com/jingyuyao/3030571e9051142c3a7ec498435a0c3c

**Comment by Marcono1234** [comment] 2022-07-24 21:27
Probably a duplicate of #526

**Comment by eamonnmcmanus** [comment] 2022-07-25 18:02
Closing as a duplicate. It _would_ be good if we had a better story for Gson and Guava, but that is covered by #526 I think.

**Closed by eamonnmcmanus** 2022-07-25 18:02 UTC
