### ISSUE TITLE
Java 9 Requirement in GSON Library

### ISSUE THREAD

**Issue by amitjoy** [google/gson#1608] opened 2019-11-06 13:39 UTC
The newest version 2.8.6 comprises the following in its MANIFEST.MF

`Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=9.0))"`

This prevents the bundle to be installed in Java 8 execution environment. Is there really any Java 9 dependency in this version at all? I hope not since the patch version is only bumped up and the 2.8.5 version is compatible with Java 8.

**Comment by inder123** [comment] 2019-11-06 19:23
Yes, this is a bug that we will fix soon. Can you test the latest snapshot to see if the issue is gone?

**Comment by elharo** [comment] 2019-11-07 14:30
This is a dupe of #1601. It's fixed at head. When is the next release with this fix scheduled?

**Comment by amitjoy** [comment] 2019-11-07 14:31
@inder123 I just noticed. It has already been fixed.

**Comment by chanseokoh** [comment] 2019-11-08 23:06
#1601 (and this one as a dup) fixed by #1603. Please close this.

**Closed** 2019-11-08 23:16 UTC

**Comment by markwoon** [comment] 2019-12-19 23:18
Can we please get a new release to fix this?  Pretty please?  Before Christmas?
