### ISSUE TITLE
Android 4.2.2 native Crash by using gson  SIGSEGV(SEGV_ACCERR)

### ISSUE THREAD

**Issue by CrashHunter** [google/gson#946] opened 2016-10-24 06:52 UTC
#28971 Thread-28971

SIGSEGV(SEGV_ACCERR)

1 #00 pc 425a0978 <unknown>
2 #01 pc 0005de78 /system/lib/libdvm.so [armeabi-v7a]
3 java:
4 com.google.gson.Gson.com.google.gson.TypeAdapter getAdapter(com.google.gson.reflect.TypeToken)(Gson.java:358)
5 com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.com.google.gson.TypeAdapter getFieldAdapter(com.google.gson.Gson,java.lang.reflect.Field,com.google.gson.reflect.TypeToken)(ReflectiveTypeAdapterFactory.java:109)
6 com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.access$100(ReflectiveTypeAdapterFactory.java:46)
7 com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.void <init>(com.google.gson.internal.bind.ReflectiveTypeAdapterFactory,java.lang.String,boolean,boolean,com.google.gson.Gson,java.lang.reflect.Field,com.google.gson.reflect.TypeToken,boolean)(ReflectiveTypeAdapterFactory.java:84)
8 com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$BoundField createBoundField(com.google.gson.Gson,java.lang.reflect.Field,java.lang.String,com.google.gson.reflect.TypeToken,boolean,boolean)(ReflectiveTypeAdapterFactory.java:83)
9 com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.java.util.Map getBoundFields(com.google.gson.Gson,com.google.gson.reflect.TypeToken,java.lang.Class)(ReflectiveTypeAdapterFactory.java:129)
10 com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.com.google.gson.TypeAdapter create(com.google.gson.Gson,com.google.gson.reflect.TypeToken)(ReflectiveTypeAdapterFactory.java:75)
11 com.google.gson.Gson.com.google.gson.TypeAdapter getAdapter(com.google.gson.reflect.TypeToken)(Gson.java:358)
12 com.google.gson.Gson.java.lang.Object fromJson(com.google.gson.stream.JsonReader,java.lang.reflect.Type)(Gson.java:804)
13 com.google.gson.Gson.java.lang.Object fromJson(java.io.Reader,java.lang.reflect.Type)(Gson.java:770)
14 com.google.gson.Gson.java.lang.Object fromJson(java.lang.String,java.lang.reflect.Type)(Gson.java:719)
15 com.google.gson.Gson.java.lang.Object fromJson(java.lang.String,java.lang.Class)(Gson.java:691)

code:
result = mGson.fromJson(value, MGLoginData.Result.class);

Someone help me?

**Comment by Marcono1234** [comment] 2024-07-21 15:11
I am going to close this issue since it is quite old, and at least from the stack trace it is not clear why that code would cause a native crash.

If you still experience this issue with the latest Gson version, please create a new issue, ideally with a small self contained example for reproducing this, and information about the Android device.

**Closed by Marcono1234** 2024-07-21 15:11 UTC
