### ISSUE TITLE
Seems like bug of LinkedTreeMap

### ISSUE THREAD

**Issue by bigsquirrel** [google/gson#2146] opened 2022-07-18 06:58 UTC
Main logic of code, 

```Java
String jsonStr = "";
Map<String, TypeConfig> configTypeMap = gson.fromJson(jsonStr, new TypeToken<Map<String, TypeConfig>>() {}.getType());
    
// not null
Map<String, TypeConfig> dbTypeMap = queryTypeMap();
configTypeMap.putAll(dbTypeMap);

```

Sometimes produce npe online, even dbTypeMap or configTypeMap is not null.

```Java
java.lang.NullPointerException: null
	at com.google.gson.internal.LinkedTreeMap.rotateLeft(LinkedTreeMap.java:376) ~[gson-2.8.6.jar:?]
	at com.google.gson.internal.LinkedTreeMap.rebalance(LinkedTreeMap.java:347) ~[gson-2.8.6.jar:?]
	at com.google.gson.internal.LinkedTreeMap.find(LinkedTreeMap.java:175) ~[gson-2.8.6.jar:?]
	at com.google.gson.internal.LinkedTreeMap.put(LinkedTreeMap.java:94) ~[gson-2.8.6.jar:?]
	at java.util.AbstractMap.putAll(AbstractMap.java:281) ~[?:1.8.0_292]
```

**Comment by Marcono1234** [comment] 2022-07-19 12:23
It looks like you are using Gson 2.8.6, could you please try it with the latest version (currently 2.9.0) as well just to be sure? Even though the Git history does not show any significant changes for `LinkedTreeMap` between these versions.

Could you please try to create a small self-contained example? Without knowing the exact value of `jsonStr` and the return value of `queryTypeMap()`, it is difficult to reproduce this. Additionally, is `configTypeMap` modified concurrently by multiple threads?

**Comment by Marcono1234** [comment] 2024-01-07 22:48
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.

**Closed by Marcono1234** 2024-01-07 22:48 UTC
Labels: bug, needs-info

**Comment by aliakberaakashdh** [comment] 2024-09-26 12:51
Hi,
I'm having a similar issue,
This is the stacktrace:
```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'com.google.gson.internal.LinkedTreeMap$Node com.google.gson.internal.LinkedTreeMap$Node.b' on a null object reference
       at com.google.gson.internal.LinkedTreeMap.rotateRight(LinkedTreeMap.java:427)
       at com.google.gson.internal.LinkedTreeMap.rebalance(LinkedTreeMap.java:372)
       at com.google.gson.internal.LinkedTreeMap.find(LinkedTreeMap.java:205)
       at com.google.gson.internal.LinkedTreeMap.put(LinkedTreeMap.java:123)
       at com.google.gson.JsonObject.add(JsonObject.java:70)
       at com.google.gson.JsonObject.addProperty(JsonObject.java:94)
```
I'm using Gson version: `2.11.0`
I'm using another library which is calling `JsonObject.addProperty`, but I'm 100% sure that it's not sending a null property as it's being called from kotlin code and the value is non nullable.
Any pointers on what could be a possible fix?

**Comment by Marcono1234** [comment] 2024-09-26 13:16
@aliakberaakashdh, thanks for the information. A few questions:
- Does this occur on a JDK or on Android?
- It seems the Gson classes have been partially obfuscated, your exception shows field name `b` but the field is named `left` in the original code
Does this still occur when you disable the code obfuscator, probably R8?[^1]
- Are you able to consistently reproduce this, and if so could you please share a small example?
- Is there concurrency involved, and could it be the case that another thread is concurrently modifying the map?

[^1]: Not that this is a proper solution, but might help determining if somehow R8 introduced this bug.

**Comment by aliakberaakashdh** [comment] 2024-09-26 13:41
Hey @Marcono1234 ,
Thanks for the suggestion. To answer your questions
1. It's ocurring on Android
2. This is only happening very rarely in production so I'm not able to reproduce it.
3. Yes concurrency is involved.

I will try to synchronise it's usage and observe if it's still occurring.
