### ISSUE TITLE
Some unittest of DefaultDateTypeAdapterTest failed

### ISSUE THREAD

**Issue by clovertrail** [google/gson#1185] opened 2017-11-01 06:09 UTC
I run gson 2.8.2 on Windows 10 with oracle JDK 9.0.1, and found I failed to build the package.

The date serialization is not expected. See the below trace stack.

junit.framework.ComparisonFailure: expected:<"Jan 1, 1970[] 12:00:00 AM"> but was:<"Jan 1, 1970[,] 12:00:00 AM">
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at junit.framework.TestCase.assertEquals(TestCase.java:269)
	at com.google.gson.DefaultDateTypeAdapterTest.assertFormatted(DefaultDateTypeAdapterTest.java:180)
	at com.google.gson.DefaultDateTypeAdapterTest.assertFormattingAlwaysEmitsUsLocale(DefaultDateTypeAdapterTest.java:49)
	at com.google.gson.DefaultDateTypeAdapterTest.testFormattingInEnUs(DefaultDateTypeAdapterTest.java:35)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)

**Comment by davido** [comment] 2017-12-10 09:19
I ran into similar issue, when porting Gerrit Code Review to Java 9: [1].

Intrestingly, this porblem doesn't occur, when tests executed from Eclipse,
but only from Bazel build tool.

So, for some reasons, the SimpleDateFormat(DateFormat).format(Date) under Bazel
produces "Feb 7, 2017, 2:20:30 AM" instead of expected: "Feb 7, 2017 2:20:30 AM".

[1] https://monorail-prod.appspot.com/p/gerrit/issues/detail?id=7902

**Comment by davido** [comment] 2017-12-10 10:42
It doesn't really seem to be GSon related. It looks like Java 9 behaviour changed.

I created this reproducer:  https://github.com/davido/date_format_java9_produces_different_result_as_java8 and verified, that on both Bazel und Maven, thre results differ in the same way: the test passes on java 8, but fails on Java 9.

**Comment by cheister** [comment] 2017-12-10 16:07
This is caused by a change the default locale data in Java 9 to use Unicode Common Locale Data Repository (CLDR)  https://docs.oracle.com/javase/9/intl/internationalization-enhancements-jdk-9.htm#JSINT-GUID-9DCDB41C-A989-4220-8140-DBFB844A0FCA  If you pass `-Djava.locale.providers=COMPAT,CLDR,SPI` to the jvm then you get the JDK 8 behavior.

**Comment by Marcono1234** [comment] 2022-08-02 23:22
Looks like this was fixed by #1211.

**Closed by Marcono1234** 2022-08-02 23:22 UTC
