### ISSUE TITLE
Returning null arrays when use toJson parsing arraylist

### ISSUE THREAD

**Issue by adrisonjrgomez** [google/gson#1483] opened 2019-03-06 14:48 UTC
hellow igotsome trouble trying to parse a list to json returnig null element

**Comment by Ad0197** [comment] 2019-03-06 15:02
the problem is the following
`list = db.mostrar() //returning a object collection with 2 object
`return new Gson().toJson(list); //returning [null],[null]`

**Comment by JakeWharton** [comment] 2019-03-06 16:54
Please provide a failing test case that demonstrates the beahvior.

**Comment by Marcono1234** [comment] 2024-01-07 22:38
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.

**Closed by Marcono1234** 2024-01-07 22:38 UTC
Labels: needs-info
