### ISSUE TITLE
$Gson$Types.resolve() infinite recursion fix introduces insufficient recursion problem

### ISSUE THREAD

**Issue by sgo-acerta** [google/gson#1876] opened 2021-03-23 15:52 UTC
See the junit test below.
This test will pass on 2.8.1 but fails since 2.8.2

```
import com.google.gson.*;
import org.junit.Test;

import java.lang.reflect.Type;
import java.util.List;

import static org.junit.Assert.assertEquals;

public class SandboxTest {
    Gson gson = new GsonBuilder().registerTypeAdapter(CustomReason.class, new TestAdapter()).create();

    @Test
    public void reason_can_not_be_parsed() {
        CustomRoot result = gson.fromJson("{\"feedbackList\": [{\"reason\": \"my custom reason\"}]}", CustomRoot.class);
        assertEquals("my custom reason", result.feedbackList.stream().map(it -> it.reason.value).findFirst().get());
    }

    public interface Reason {
    }

    public static class Root<R extends Reason, F extends Feedback<R>> {
        List<F> feedbackList;
    }

    public static class FeedbackRoot<R extends Reason> extends Root<R, Feedback<R>> {

    }

    public static class Feedback<R extends Reason> {
        private R reason;
    }

    public static class CustomReason implements Reason {
        private String value;

        public CustomReason(String value) {
            this.value = value;
        }
    }

    public static class CustomRoot extends FeedbackRoot<CustomReason> {
    }

    private class TestAdapter implements JsonDeserializer<CustomReason> {
        public CustomReason deserialize(JsonElement jsonElement, Type type, JsonDeserializationContext jsonDeserializationContext) throws JsonParseException {
            return new CustomReason(jsonElement.getAsString());
        }
    }
}
```

**Comment by Marcono1234** [comment] 2021-03-24 17:56
Sounds like #1391 would fix this.

**Comment by Marcono1234** [comment] 2022-08-03 23:29
Cannot reproduce this with Gson 2.9.1 so I assume it was fixed indeed. Please let us know if you still experience this issue with the latest Gson versions.

**Closed by Marcono1234** 2022-08-03 23:29 UTC
