### ISSUE TITLE
Occasional NullPointerException when calling Gson.fromJson when converting to a TypedToken of type CopyOnWriteArraySet

### ISSUE THREAD

**Issue by kalyandechiraju** [google/gson#2070] opened 2022-02-03 03:54 UTC
# Gson version
2.8.9

# Java / Android version
Multiple Android versions (23+)

# Description
NullPointerException when calling Gson.fromJson when converting to a TypedToken of type CopyOnWriteArraySet. 
This crash is noticed on user devices but not reproducible locally while debugging.

Here is the code that is causing the null pointer.
```
        CopyOnWriteArraySet<String> result;
        Type type = new TypeToken<CopyOnWriteArraySet<String>>() {
        }.getType();
        Gson gson = new Gson();
        result = gson.fromJson(json, type);
```

# Exception stack trace
<img width="815" alt="Screenshot 2022-02-03 at 9 14 30 AM" src="https://user-images.githubusercontent.com/6111841/152278262-66c53048-64f0-49a2-ad44-1aa47816e5c4.png">

```

```

**Comment by Marcono1234** [comment] 2022-02-03 18:24
Looks like a duplicate of #1778

**Comment by kalyandechiraju** [comment] 2022-02-14 10:17
Any suggestions for fixing this? The above mentioned issue seems to be open as well.

**Comment by Marcono1234** [comment] 2022-02-14 15:30
No, sorry I am not aware of any. As mentioned in that issue, it is not completely clear why and under which circumstances the problem is occurring. Are you able to consistently reproduce this?

If so, could you please make sure to apply all ProGuard rules from [`proguard.cfg`](https://github.com/google/gson/blob/master/examples/android-proguard-example/proguard.cfg) (except the one for `com.google.gson.examples.android.model.**`), in case you aren't using them already.

**Comment by kalyandechiraju** [comment] 2022-02-15 08:25
I got your point. Sure will use the proguard rules as per that sample app and will observe the results.

**Comment by BoboBirdFly** [comment] 2022-08-25 10:27
did using proguard rules solve the problem?

**Comment by kalyandechiraju** [comment] 2022-08-25 10:51
Apparently the issue got fixed when we made the below two changes:
1. Add complete proguard rules as per documentation
2. Avoid casting json directly to `CopyOnWriteArraySet`. Instead casted in to an `ArrayList` and then pass it to constructor of `CopyOnWriteArraySet`.

**Comment by BoboBirdFly** [comment] 2022-08-25 10:58
thanks! I'll try it

**Comment by Marcono1234** [comment] 2024-07-22 22:43
I am going to close this issue since this is likely a duplicate of #1778

**Closed by Marcono1234** 2024-07-22 22:43 UTC
Labels: bug
