### ISSUE TITLE
 RuntimeException:Missing type parameter

### ISSUE THREAD

**Issue by peterWater** [google/gson#1822] opened 2020-11-23 03:14 UTC
code:
new TypeToken<Advertisement>()

build.gradle:
 release {
            //是否是debug模式
            debuggable false
            // 代码混淆
            minifyEnabled true
            // Zipalign优化
            zipAlignEnabled true
            // 移除无用的resource文件
            shrinkResources true
            // applicationIdSuffix ".release"
            signingConfig signingConfigs.stagingConfig

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro','mpProguard.cfg'
        }

Error:
java.lang.RuntimeException: Missing type parameter.
        at com.google.gson.reflect.TypeToken.getSuperclassTypeParameter()
        at com.google.gson.reflect.TypeToken.<init>()
        at kds.szkingdom.modemain.android.phone.AppInitService$2.<init>(AppInitService.java:481)
        at com.bangcle.andJni.JniLib1605768589.cV(Native Method)
        at kds.szkingdom.modemain.android.phone.AppInitService.reqAdvInitData(AppInitService.java)
        at com.bangcle.andJni.JniLib1605768589.cV(Native Method)

**Comment by Marcono1234** [comment] 2022-02-02 00:12
The issue is probably that you are calling `new TypeToken()`, that is you are using a _raw type_  instead of providing type arguments, e.g. `new TypeToken<...>()`. See also [this StackOverflow answer](https://stackoverflow.com/a/49857169).

**Comment by Marcono1234** [comment] 2022-08-05 22:06
Are you still experiencing this issue?

**Comment by Marcono1234** [comment] 2024-01-07 22:38
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.

**Closed by Marcono1234** 2024-01-07 22:38 UTC
Labels: needs-info
