### ISSUE TITLE
Incorrect parsing JSON object

### ISSUE THREAD

**Issue by alexokok** [google/gson#2272] opened 2022-12-07 17:04 UTC
# Gson version 
2.8.6

# Java / Android version
Kotlin 1.7.10

# Used tools
- Gradle: 4.1.3 

# Description
I send to Gson string like "{ "foo" = "something", "bar"="nothing"} and  Gson parse it well. 

## Expected behaviour
Gson needs to throw JsonSyntaxException

## Actual behavior
Gson parse JSON string in object well 

Is it expected behaviour?

**Comment by eamonnmcmanus** [comment] 2022-12-07 18:36
I think this is a duplicate of #1208. The current behaviour is very unfortunate, and it might be worth investigating a `GsonBuilder.setStrict` method or something.

**Closed by eamonnmcmanus** 2022-12-07 18:36 UTC
Labels: bug, duplicate

**Comment by Marcono1234** [comment] 2022-12-07 22:29
See also the "Lenient JSON handling" section of the [`Gson` class documentation](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/Gson.html).
