### ISSUE TITLE
serialize date sometimes TreeTypeAdapter, sometimes DefaultDateTypeAdapter?

### ISSUE THREAD

**Issue by rala7** [google/gson#1095] opened 2017-06-01 08:51 UTC
It's weird with Gson version 2.8.1.

I use gson.toJson( myBizObj );
In command lines or tomcat got nullpointexception, but in eclipse it works well.

So, I hacked com.google.gson.internal.bind.ReflectiveTypeAdapterFactory to get some logs.
In line 120:
` @Override void write(JsonWriter writer, Object value)
          throws IOException, IllegalAccessException {
        Object fieldValue = field.get(value);
        TypeAdapter t = jsonAdapterPresent ? typeAdapter
            : new TypeAdapterRuntimeTypeWrapper(context, typeAdapter, fieldType.getType());
        System.out.println("\tvalue:"+fieldValue);
        System.out.println("\ttypeAdapter:"+typeAdapter.getClass());
        t.write(writer, fieldValue);
      }`

When I run test with gradle command: `gradle test --tests ....`
Log is:

> write json field：regDate
> 	value:null
> 	typeAdapter:class com.google.gson.DefaultDateTypeAdapter

When I run in eclipse:
Log is:

> write json field：regDate
> 	value:null
> 	typeAdapter:class com.google.gson.internal.bind.TreeTypeAdapter

Q1: why different adapter, in different runtime?
Q2: why DefaultDateTypeAdapter can't handle null value?

Thanks.

**Comment by lyubomyr-shaydariv** [comment] 2017-06-09 05:31
> Q2: why DefaultDateTypeAdapter can't handle null value?

There was my regression commit that was unfortunately released with 2.8.1. Should be fixed in the linked PR.

**Comment by lyubomyr-shaydariv** [comment] 2017-06-09 05:52
> Q1: why different adapter, in different runtime?

Are you really sure to have Gson 2.8.1 for both cases? Gson 2.8.1 should pick `DefaultDateTypeAdapter` only.

**Comment by Marcono1234** [comment] 2024-05-20 03:13
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.

**Closed by Marcono1234** 2024-05-20 03:13 UTC
