### ISSUE TITLE
gson parse success for json strings that have an invalid escape sequence

### ISSUE THREAD

**Issue by nkarkala** [google/gson#824] opened 2016-04-07 00:37 UTC
I am basically doing the following,

`JsonElement jsonElement = new JsonParser().parse(config);  
`

When the config string is for example : {"userName": "ab\cd"} which has an invalid escape sequence (\c), instead of getting a parse error, it appears that the escape character is just being removed. Hence the resulting jsonElement has "userName": "abcd". 

Looking at the code base in the JsonReader class, I see that when a valid escape sequence is not matched , it is simply ignored (default case) rather than throwing an invalid json error. Is this behavior intended?  This is critical since I fail to catch the error and end up using a modified string (i.e with escape character removed) . 

```
private char readEscapeCharacter() throws IOException {
    if (pos == limit && !fillBuffer(1)) {
      throw syntaxError("Unterminated escape sequence");
    }

    char escaped = buffer[pos++];
    switch (escaped) {
    case 'u':
      if (pos + 4 > limit && !fillBuffer(4)) {
        throw syntaxError("Unterminated escape sequence");
      }
      // Equivalent to Integer.parseInt(stringPool.get(buffer, pos, 4), 16);
      char result = 0;
      for (int i = pos, end = i + 4; i < end; i++) {
        char c = buffer[i];
        result <<= 4;
        if (c >= '0' && c <= '9') {
          result += (c - '0');
        } else if (c >= 'a' && c <= 'f') {
          result += (c - 'a' + 10);
        } else if (c >= 'A' && c <= 'F') {
          result += (c - 'A' + 10);
        } else {
          throw new NumberFormatException("\\u" + new String(buffer, pos, 4));
        }
      }
      pos += 4;
      return result;

    case 't':
      return '\t';

    case 'b':
      return '\b';

    case 'n':
      return '\n';

    case 'r':
      return '\r';

    case 'f':
      return '\f';

    case '\n':
      lineNumber++;
      lineStart = pos;
      // fall-through

    case '\'':
    case '"':
    case '\\':
   default:
      return escaped;
    }
  } 
```

**Comment by JMVM** [comment] 2016-04-28 10:13
Related to this issue, there is another one when having for example a date with double-slash escaped solidus character (in my case: "date":"27\\/4\\/2016").

Having the look **JsonReader class ** too, the escaped character is **/**, being returned by default. So far so good, having the same behavior than escaped **\a**, returning character **a**. However, in this case, getting an exception from **Gson class**:

**Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 23**

Debugging on assertion which throws the exception, it looks like the process finished too early due to that returned character, since in the object there is not all the data from JSON.

**assertFullConsumption(object, jsonReader);**

Obviously, it looks like a date format mistake in JSON response, but I think Gson should control better this situation.

Thanks

**Comment by Marcono1234** [comment] 2023-08-16 19:12
I am going to close this beacuse as mentioned above this was merged manually.

**Closed by Marcono1234** 2023-08-16 19:12 UTC
