### ISSUE TITLE
incorrect buffer filling and false EOF

### ISSUE THREAD

**Issue by olicht** [google/gson#1234] opened 2018-01-25 10:57 UTC
When reading the following `graph.txt` (originally `.json`), I get the following error: 

```java
com.google.gson.JsonSyntaxException: java.io.EOFException: End of input at line 1 column 1025 path $.edges[3].weight
                      at com.google.gson.Gson.fromJson(Gson.java:898)
                      at com.google.gson.Gson.fromJson(Gson.java:853)
                      at com.google.gson.Gson.fromJson(Gson.java:802)
```

When I went down the rabbit hole I discovered that on `java.lang.Thread.State: RUNNABLE
	  at com.google.gson.stream.JsonReader.peek(JsonReader.java:453)`, when `p=16`, instead of returning with `JsonToken.NUMBER`, it continued to the next case and returned `JsonToken.END_DOCUMENT`. 

For your convenience, I've attached dump from before and after the bug (col 1023,1024 and col 1025), and when I went WTF???. 
[Gson just before crush (1023).txt](https://github.com/google/gson/files/1663563/Gson.just.before.crush.1023.txt)
[Gson just before crush (1024).txt](https://github.com/google/gson/files/1663565/Gson.just.before.crush.1024.txt)
[Gson just after crush (1025).txt](https://github.com/google/gson/files/1663569/Gson.just.after.crush.1025.txt)
[Gson WTF - should have returned.txt](https://github.com/google/gson/files/1663579/Gson.WTF.-.should.have.returned.txt)
 
If you need, the following code was used (`.java` was replaced with `.java.txt` to get around GitHub exclusions):

- ```java
        Gson gson = new Gson();
        InputStream is = getResources().openRawResource(R.raw.graph);
        String json = (new Scanner(is)).useDelimiter("\\Z").next();
        WeightedGraph<LocationDataPoint> TestGraph = gson.fromJson(json, new TypeToken<WeightedGraph<LocationDataPoint>>(){}.getType()); ```
- [LocationDataPoint.java.txt](https://github.com/google/gson/files/1663591/LocationDataPoint.java.txt)
- [WeightedGraph.java.txt](https://github.com/google/gson/files/1663593/WeightedGraph.java.txt)
- [Vertex.java.txt](https://github.com/google/gson/files/1663597/Vertex.java.txt)
- [Graph.java.txt](https://github.com/google/gson/files/1663599/Graph.java.txt)
- [Edge.java.txt](https://github.com/google/gson/files/1663601/Edge.java.txt)

**The `graph.json` was created by Gson, so it should be compatible with Gson...**

[graph.txt](https://github.com/google/gson/files/1663513/graph.txt)

**Comment by olicht** [comment] 2018-02-10 14:43
Any new about this issue? @amogilev

**Comment by olicht** [comment] 2018-03-17 17:17
Any update?
Did a maintainer looked at this issue?
Can I get anybody to replay to this issue?

**Comment by trusitshah** [comment] 2018-10-23 22:51
I got a similar issue in my android app. 

Caused by com.google.gson.JsonSyntaxException: java.io.EOFException: End of input at line 1 column 225931 path $.data.polygons[220].paths[14].lat
       at com.google.gson.Gson.fromJson(Gson.java:898)
       at com.google.gson.Gson.fromJson(Gson.java:853)
       at com.google.gson.Gson.fromJson(Gson.java:802)
       at com.google.gson.Gson.fromJson(Gson.java:774)

**Comment by GuilhermeGSousa** [comment] 2019-07-19 16:16
Any updates on this issue?

**Comment by GuilhermeGSousa** [comment] 2019-07-22 16:07
This error can be avoided by passing `InputStreamReader` as a parameter to the `fromJson` method. In my case this error was caused by some lack of memory problems on some devices and the reader's stream reaches its end before the actual end of your json.

**Comment by Marcono1234** [comment] 2022-09-18 21:48
> This error can be avoided by passing `InputStreamReader` as a parameter to the `fromJson` method. In my case this error was caused by some lack of memory problems on some devices and the reader's stream reaches its end before the actual end of your json.

That is actually a good point; the [documentation for `Scanner`](https://developer.android.com/reference/java/util/Scanner?hl=en) says:

> If an invocation of the underlying readable's `Readable.read(CharBuffer)` method throws an `IOException` then the scanner assumes that the end of the input has been reached. The most recent `IOException` thrown by the underlying readable can be retrieved via the `ioException()` method.

So it could indeed be the case that the underlying stream threw an exception and `Scanner` silently considered it as end of stream. In case anyone is still experiencing this, could you please make sure you experience this even without using `Scanner`? Please also try the latest Gson version.

**Comment by Marcono1234** [comment] 2024-01-07 23:18
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.

**Closed by Marcono1234** 2024-01-07 23:18 UTC
Labels: needs-info
